spring.application.name=GymLogCore
spring.datasource.url=jdbc:postgresql://localhost:5432/gymlog_db
spring.datasource.username=gym_admin
spring.datasource.password=secret_password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect